# Generated by Django 5.1.6 on 2025-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.CharField(default='', max_length=500, verbose_name='Video'),
        ),
    ]
